config/routes.rb
Rails.application.routes.draw do
  resources :sources do
    resources :comments, only: [:create]
  end
  root 'sources#index'
  resources :sessions

  get 'login', :to => 'sessions#new', as: 'login'
  get 'logout', :to => 'sessions#destroy', as: 'logout'
  post 'sessions/try_login'    
  post 'followings/follow'
  delete 'followings/unfollow'  
  delete 'comments/destroy'

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/source.rb
class Source < ApplicationRecord
  validates :text, presence: true, length: { maximum: 500 }
  belongs_to :author, class_name: 'User'
  has_many :comments
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  include ApplicationHelper

  before_action :check_login
  before_action :set_source, only: %i[show edit update destroy]

  # GET /sources
  # GET /sources.json
  def index
    @source = Source.new
    @sources = Source.order('created_at DESC').includes(:author, :comments)
    @users = User.where.not(id: current_user).limit(15)
    @following = User.find(current_user).followeds
  end

  # GET /sources/1
  # GET /sources/1.json
  def show; end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit; end

  # POST /sources
  # POST /sources.json
  def create
    if current_user
      @source = User.find(current_user).sources.new(source_params)
    else
      flash[:notice] = 'you need to be logged in to create posts!'
      redirect_to sources_path
    end

    respond_to do |format|
      if @source.save
        format.html { redirect_to request.referrer, notice: 'Source was successfully created.' }
        format.json { render :show, status: :created, location: @source }
      else
        format.html { render :new }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
    respond_to do |format|
      if @source.update(source_params)
        format.html { redirect_to @source, notice: 'Source was successfully updated.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
    if @source.destroy
      redirect_to sources_url, notice: 'Source was successfully destroyed.'
    else
      redirect_to request.referrer, notice: 'Source did not get destroyed.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_source
    @source = Source.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def source_params
    params.require(:source).permit(:text)
  end
end

app/helpers/sources_helper.rb
module SourcesHelper
  def source_links(source)
    content = content_tag(:div)
    if source.author.id == current_user
      content << link_to('Show', source)
      content << link_to('Edit', edit_source_path(source))
      content << link_to('Destroy', source, method: :delete, data: { confirm: 'Are you sure?' })
    end
    content
  end
end

app/views/sources/_form.html.erb
<%= form_for(@source) do |f| %>


  <div class="field">
    <%= f.text_field :text, placeholder: 'Compose new source' %>
  </div>

  <div>
    <%= f.submit :Submit, class: 'button is-primary' %>
  </div>
<% end %>

app/views/sources/edit.html.erb
<h1>Editing Sources</h1>

<%= render 'form', source: @source %>

<%= link_to 'Show', @source %> |
<%= link_to 'Back', sources_path %>

app/views/sources/index.html.erb
<div class="source-index-content">
  <div class="columns source-index-cols">
    <div class="column is-9">
      <div class="link-panel">
        <a href="#" class='active'>Sources</a>     
      </div>
      <div class="card source-index-new">
          <p>Share Source</p>
          <%= render('form') %>        
      </div>
      <div class="card source-index-list">
        <h5 class='new-source-count'>6 New Sources</h5>      
        <% @sources.each do |source| %>            
          <div class='source-item'>
            <div class="columns">
              <div class="column is-1">
              <figure class='image is-48x48'>
                <%= image_tag profile_img(source.author), class: 'is-roundish' %>
              </figure>
              </div>              
              <div class="column">
                <h4 class='source-author'>
                  <%= link_to source.author.full_name.capitalize, user_path(source.author) %>
                </h4>
                <div>              
                  <p><%= source.text %></p>
                </div>
                <div>
                <%= source_links(source) %>
                </div>
                <div class="comments">
                  <% source.comments.each do |comment| %>
                    <div class="comment">
                      <h4><%= comment.user.full_name %></h4>
                      <p><%= comment.text %></p>
                      <%= destroy_comment(comment) %>
                    </div>
                  <% end %>

                  <%= form_for(source.comments.new, url: source_comments_path(source)) do |f| %>
                    <%= f.text_field :text, placeholder: 'New Comment' %>
                    <%= f.submit 'Comment', class: 'button is-primary' %>
                  <% end %>
                </div>
              </div>              
            </div>
          </div>         
        <% end %>      
      </div>
    </div>
    <div class="column">
      <div class="who-to-follow"> 
        <h3>Who to follow</h3>
        <% @users.each do |user| %>
          <% unless @following.include?(user) %>
            <div class='follow-item'>
              <div class="columns">
                <div class="column is-3">
                  <figure class='image is-48x48'>
                    <%= image_tag 'profile.png', class: 'is-rounded' %>
                  </figure>                  
                </div>
                <div class="column">
                  <h4><%= link_to user.full_name, user_path(user) %></h4>                                
                    <%= link_to 'Follow', followings_follow_path(follower_id: current_user, followed_id: user.id), method: :post, class: 'follow-link' %>                
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sources/new.html.erb
<h1>New Sources</h1>

<%= render 'form', source: @source %>

<%= link_to 'Back', sources_path %>

app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Authors:</strong>
  <%= @source.author_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @source.text %>
</p>

<%= link_to 'Edit', edit_source_path(@source) %> |
<%= link_to 'Back', sources_path %>