config/routes.rb
Rails.application.routes.draw do
  resources :sources do
    resources :comments, only: [:create]
  end
  root 'sources#index'
  resources :sessions

  get 'login', :to => 'sessions#new', as: 'login'
  get 'logout', :to => 'sessions#destroy', as: 'logout'
  post 'sessions/try_login'    
  post 'followings/follow'
  delete 'followings/unfollow'  
  delete 'comments/destroy'

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_side_nav.html.erb
<div class="columns user-profile">
  <div class="column is-one-quarter">
    <figure class='image is-48x48'>     
      <%= image_tag session[:photo], class: 'is-roundish' %>
    </figure>
  </div>
  <div class="column is-three-quarters">
    <span><%= !session[:user_id].nil? ? session[:name] : ': )' %></span>
  </div>
</div>


<% if current_user %>
<div class="columns user-follow-stats">
  <div class="column is-half">
    <a href="#"><%= session[:followeds] %><br><span>Following</span></a>
  </div>
  <div class="column is-half">
    <a href="#"><%= session[:followers] %><br><span>Followers</span></a>
  </div>
</div>   

<ul class='side-nav-links'>
  <li>
    <%= link_to sources_path do  %>
      <%= image_tag 'home.svg', class: 'image is-16x16' %>
      <span>Home</span>
    <% end %>  
  </li> 
  <li> 
    <%= link_to users_path do  %>
      <%= image_tag 'explore.svg', class: 'image is-16x16' %>
      <span>Discover</span>
    <% end %>
  </li>
  <li> 
    <%= link_to user_path(current_user) do  %>
      <%= image_tag 'user.svg', class: 'image is-16x16' %>
      <span>Profile</span>
    <% end %>
  </li>
</ul>
    
 
<% end %>

app/views/shared/_top_nav.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="<%= root_path %>"> 
      <%= image_tag 'crystal-ball.svg', class: 'image is-64x64' %>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">   
    <div class="navbar-end">      
      <div class="navbar-item">      
        <div class="buttons">          
          <% if current_user %>
            <%= link_to 'Logout', logout_path, class: 'button is-primary' %>
          <% else %>
            <%= link_to 'login', login_path, class: 'button is-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>